export type Brand = "ASUS" | "Lenovo" | "MSI" | "Acer" | "HP" | "Dell" | "GIGABYTE";
export type CpuFamily =
  | "Intel Core i5"
  | "Intel Core i7"
  | "Intel Core i9"
  | "Intel Core Ultra 7"
  | "Intel Core Ultra 9"
  | "AMD Ryzen 7"
  | "AMD Ryzen 9"
  | "AMD Ryzen AI 9"
  | "Snapdragon X Elite";
export type GpuFamily =
  | "Iris Xe"
  | "Intel Arc"
  | "RTX 3050"
  | "RTX 4050"
  | "RTX 4060"
  | "RTX 4070"
  | "RTX 4080"
  | "RTX 4090";
export type Need =
  | "Gaming"
  | "Văn phòng"
  | "Đồ họa"
  | "Sinh viên"
  | "Mỏng nhẹ"
  | "Cảm ứng"
  | "Laptop AI";

export interface VariantOption {
  ram: 8 | 16 | 32 | 64;
  ssd: 256 | 512 | 1024 | 2048;
  priceDelta: number;
}

export interface Product {
  id: string;
  slug: string;
  name: string;
  brand: Brand;
  needs: Need[];
  cpu: CpuFamily;
  gpu: GpuFamily;
  basePrice: number;
  originalPrice?: number;
  isSale?: boolean;
  display: string;
  battery: string;
  weight: string;
  warranty: string;
  variants: VariantOption[];
  images: string[];
  anhDaiDien?: string;
  badge?: "Flash Sale" | "Mới" | "Bán chạy";
  rating: number;
  reviewCount: number;
  /** Tồn kho từ API soLuongTon */
  stockQuantity?: number;
  description: string;
  /** Từ API: ram */
  ram?: string;
  /** Từ API: oCung */
  storage?: string;
  /** Từ API: heDieuHanh */
  heDieuHanh?: string;
  oCung?: string;
  manHinh?: string;
  pin?: string;
  maThuongHieu?: string | number;
  maDanhMuc?: number;
  giaGoc?: number;
  phanTramGiam?: number;
  giaKhuyenMai?: number;
  ngayKetThuc?: string;
  loaiSanPham?: string;
  loaiPhuKien?: string;
  ketNoi?: string;
  denLed?: string;
  thuongHieu?: string;
  doPhanGiai?: string;
  loaiBanPhim?: string;
  congNgheAmThanh?: string;
  thoiLuongPin?: string;
  kichThuoc?: string;
  baoHanh?: string;
}

const mk = (base: number): VariantOption[] => [
  { ram: 8, ssd: 512, priceDelta: 0 },
  { ram: 16, ssd: 512, priceDelta: Math.round(base * 0.08) },
  { ram: 16, ssd: 1024, priceDelta: Math.round(base * 0.13) },
  { ram: 32, ssd: 1024, priceDelta: Math.round(base * 0.22) },
];

const imgs = (seed: string) => [seed + "1", seed + "2", seed + "3", seed + "4"];

const BRAND_PRODUCT_IMAGES: Record<string, string> = {
  rog: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop&q=80",
  tuf: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  zenbook: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  expertbook: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  asus: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  thinkpad: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500&auto=format&fit=crop&q=80",
  legion: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  yoga: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=80",
  thinkbook: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  lenovo: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  stealth: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop&q=80",
  raider: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  katana: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  cyborg: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  modern: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  prestige: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  msi: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop&q=80",
  predator: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop&q=80",
  nitro: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  swift: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  aspire: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  acer: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  omen: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop&q=80",
  victus: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  spectre: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  envy: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  pavilion: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  hp: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  alienware: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop&q=80",
  xps: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  g15: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  g16: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  inspiron: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  latitude: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  dell: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=500&auto=format&fit=crop&q=80",
  aorus: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500&auto=format&fit=crop&q=80",
  aero: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=80",
  gigabyte: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80",
  mouse: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format&fit=crop&q=80",
  chuot: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&auto=format&fit=crop&q=80",
  keyboard: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&auto=format&fit=crop&q=80",
  phim: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&auto=format&fit=crop&q=80",
  headphone: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80",
  tai: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=80",
  sac: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500&auto=format&fit=crop&q=80",
};

export function resolveProductImageUrl(seed: string, label?: string): string {
  if (seed && /^(https?:\/\/|\/)/i.test(seed)) {
    return seed;
  }
  const text = `${seed || ""} ${label || ""}`.toLowerCase();
  for (const key of Object.keys(BRAND_PRODUCT_IMAGES)) {
    if (text.includes(key)) {
      return BRAND_PRODUCT_IMAGES[key];
    }
  }
  return "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500&auto=format&fit=crop&q=80";
}

type Seed = Omit<Product, "variants" | "images" | "rating" | "reviewCount"> & {
  rating?: number;
  reviews?: number;
};

const seed = (s: Seed): Product => {
  const defaultImg = resolveProductImageUrl(s.slug, s.name);
  const mockImgs = [defaultImg, defaultImg, defaultImg, defaultImg];
  return {
    ...s,
    rating: s.rating ?? 0,
    reviewCount: s.reviews ?? 0,
    variants: mk(s.basePrice),
    images: mockImgs,
    anhDaiDien: defaultImg,
    description: s.description ?? "",
  };
};

export const products: Product[] = [
  // ========== ASUS (10) — Gaming & Creator mạnh ==========
  seed({
    id: "as1",
    slug: "asus-rog-strix-scar-18",
    name: "ASUS ROG Strix SCAR 18",
    brand: "ASUS",
    needs: ["Gaming", "Đồ họa"],
    cpu: "Intel Core i9",
    gpu: "RTX 4090",
    basePrice: 89990000,
    originalPrice: 99990000,
    display: '18" QHD+ 240Hz Mini-LED',
    battery: "90Wh",
    weight: "3.1kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    rating: 4.9,
    description: "Flagship gaming với RTX 4090 và màn Mini-LED 240Hz đỉnh cao.",
  }),
  seed({
    id: "as2",
    slug: "asus-rog-zephyrus-g14",
    name: "ASUS ROG Zephyrus G14",
    brand: "ASUS",
    needs: ["Gaming", "Mỏng nhẹ"],
    cpu: "AMD Ryzen 9",
    gpu: "RTX 4060",
    basePrice: 34990000,
    originalPrice: 39990000,
    display: '14" 2.8K OLED 120Hz',
    battery: "76Wh",
    weight: "1.5kg",
    warranty: "24 tháng",
    badge: "Bán chạy",
    rating: 4.8,
    description: "Hiệu năng đỉnh cao trong thân máy mỏng 1.5kg, OLED 2.8K rực rỡ.",
  }),
  seed({
    id: "as3",
    slug: "asus-rog-zephyrus-g16",
    name: "ASUS ROG Zephyrus G16",
    brand: "ASUS",
    needs: ["Gaming", "Mỏng nhẹ"],
    cpu: "Intel Core Ultra 9",
    gpu: "RTX 4070",
    basePrice: 52990000,
    display: '16" 2.5K OLED 240Hz',
    battery: "90Wh",
    weight: "1.85kg",
    warranty: "24 tháng",
    rating: 4.8,
    description: "Gaming flagship mỏng nhẹ, OLED 240Hz cực mượt cho game và sáng tạo.",
  }),
  seed({
    id: "as4",
    slug: "asus-tuf-gaming-a16",
    name: "ASUS TUF Gaming A16",
    brand: "ASUS",
    needs: ["Gaming"],
    cpu: "AMD Ryzen 7",
    gpu: "RTX 4060",
    basePrice: 28990000,
    originalPrice: 32990000,
    display: '16" FHD+ 165Hz',
    battery: "90Wh",
    weight: "2.2kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming bền bỉ chuẩn quân đội, RTX 4060 chiến mọi tựa AAA.",
  }),
  seed({
    id: "as5",
    slug: "asus-tuf-gaming-f15",
    name: "ASUS TUF Gaming F15",
    brand: "ASUS",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i7",
    gpu: "RTX 4050",
    basePrice: 22490000,
    originalPrice: 24990000,
    display: '15.6" FHD 144Hz',
    battery: "48Wh",
    weight: "2.2kg",
    warranty: "24 tháng",
    description: "Gaming phổ thông giá tốt cho sinh viên đam mê eSports.",
  }),
  seed({
    id: "as6",
    slug: "asus-proart-studiobook-16-oled",
    name: "ASUS ProArt Studiobook 16 OLED",
    brand: "ASUS",
    needs: ["Đồ họa"],
    cpu: "Intel Core i9",
    gpu: "RTX 4070",
    basePrice: 64990000,
    display: '16" 3.2K OLED 120Hz',
    battery: "90Wh",
    weight: "2.4kg",
    warranty: "24 tháng",
    badge: "Mới",
    rating: 4.8,
    description: "Workstation sáng tạo với màn OLED chuẩn Pantone và Dial vật lý.",
  }),
  seed({
    id: "as7",
    slug: "asus-zenbook-14-oled",
    name: "ASUS Zenbook 14 OLED",
    brand: "ASUS",
    needs: ["Mỏng nhẹ", "Văn phòng"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 24990000,
    display: '14" 2.8K OLED 90Hz',
    battery: "75Wh",
    weight: "1.22kg",
    warranty: "24 tháng",
    badge: "Bán chạy",
    rating: 4.7,
    description: "Ultrabook mỏng nhẹ với màn OLED siêu đẹp, pin trâu.",
  }),
  seed({
    id: "as8",
    slug: "asus-zenbook-duo-oled",
    name: "ASUS Zenbook Duo OLED",
    brand: "ASUS",
    needs: ["Mỏng nhẹ", "Laptop AI", "Cảm ứng"],
    cpu: "Intel Core Ultra 9",
    gpu: "Intel Arc",
    basePrice: 49990000,
    display: '14" Dual OLED 2.8K cảm ứng',
    battery: "75Wh",
    weight: "1.65kg",
    warranty: "24 tháng",
    badge: "Mới",
    rating: 4.7,
    description: "Laptop hai màn hình OLED đột phá, sẵn sàng cho kỷ nguyên AI.",
  }),
  seed({
    id: "as9",
    slug: "asus-vivobook-15",
    name: "ASUS Vivobook 15",
    brand: "ASUS",
    needs: ["Sinh viên", "Văn phòng"],
    cpu: "Intel Core i5",
    gpu: "Iris Xe",
    basePrice: 14990000,
    originalPrice: 16990000,
    display: '15.6" FHD IPS',
    battery: "42Wh",
    weight: "1.7kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Laptop sinh viên giá tốt, đủ mạnh cho học tập và giải trí.",
  }),
  seed({
    id: "as10",
    slug: "asus-expertbook-b5",
    name: "ASUS ExpertBook B5",
    brand: "ASUS",
    needs: ["Văn phòng", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 32990000,
    display: '14" WUXGA chống chói',
    battery: "63Wh",
    weight: "1.3kg",
    warranty: "36 tháng",
    description: "Laptop doanh nhân chuẩn quân đội, bảo mật vân tay + Copilot AI.",
  }),

  // ========== Lenovo (10) — Business ThinkPad & Yoga touch ==========
  seed({
    id: "lv1",
    slug: "lenovo-thinkpad-x1-carbon-gen-12",
    name: "Lenovo ThinkPad X1 Carbon Gen 12",
    brand: "Lenovo",
    needs: ["Văn phòng", "Mỏng nhẹ"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 42990000,
    display: '14" 2.8K OLED',
    battery: "57Wh",
    weight: "1.12kg",
    warranty: "36 tháng",
    badge: "Bán chạy",
    rating: 4.9,
    description: "Biểu tượng ultrabook doanh nhân, bàn phím huyền thoại, bảo hành 3 năm.",
  }),
  seed({
    id: "lv2",
    slug: "lenovo-thinkpad-t14s-gen-5",
    name: "Lenovo ThinkPad T14s Gen 5",
    brand: "Lenovo",
    needs: ["Văn phòng"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 36990000,
    display: '14" WUXGA IPS',
    battery: "58Wh",
    weight: "1.24kg",
    warranty: "36 tháng",
    rating: 4.7,
    description: "ThinkPad mỏng nhẹ cho doanh nhân di chuyển, bảo mật cấp cao.",
  }),
  seed({
    id: "lv3",
    slug: "lenovo-thinkpad-p16-gen-2",
    name: "Lenovo ThinkPad P16 Gen 2",
    brand: "Lenovo",
    needs: ["Đồ họa"],
    cpu: "Intel Core i9",
    gpu: "RTX 4080",
    basePrice: 78990000,
    display: '16" 3.2K OLED 120Hz',
    battery: "94Wh",
    weight: "3.0kg",
    warranty: "36 tháng",
    rating: 4.8,
    description: "Mobile workstation cho dựng phim 3D, render và mô phỏng chuyên nghiệp.",
  }),
  seed({
    id: "lv4",
    slug: "lenovo-yoga-9i-2-in-1",
    name: "Lenovo Yoga 9i 2-in-1",
    brand: "Lenovo",
    needs: ["Cảm ứng", "Mỏng nhẹ"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 38990000,
    display: '14" 4K OLED cảm ứng',
    battery: "75Wh",
    weight: "1.4kg",
    warranty: "24 tháng",
    badge: "Mới",
    rating: 4.7,
    description: "Convertible 360° màn 4K OLED, loa Bowers & Wilkins, bút stylus đi kèm.",
  }),
  seed({
    id: "lv5",
    slug: "lenovo-yoga-slim-7i",
    name: "Lenovo Yoga Slim 7i",
    brand: "Lenovo",
    needs: ["Mỏng nhẹ", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 27990000,
    display: '14" 2.8K OLED 90Hz',
    battery: "70Wh",
    weight: "1.28kg",
    warranty: "24 tháng",
    description: "Ultrabook AI mỏng nhẹ với NPU Intel cho tác vụ sáng tạo thông minh.",
  }),
  seed({
    id: "lv6",
    slug: "lenovo-legion-pro-7i",
    name: "Lenovo Legion Pro 7i",
    brand: "Lenovo",
    needs: ["Gaming"],
    cpu: "Intel Core i9",
    gpu: "RTX 4080",
    basePrice: 62990000,
    display: '16" WQXGA 240Hz',
    battery: "99Wh",
    weight: "2.8kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    rating: 4.8,
    description: "Flagship gaming Legion với tản nhiệt Coldfront và RTX 4080.",
  }),
  seed({
    id: "lv7",
    slug: "lenovo-legion-slim-5",
    name: "Lenovo Legion Slim 5",
    brand: "Lenovo",
    needs: ["Gaming", "Sinh viên"],
    cpu: "AMD Ryzen 7",
    gpu: "RTX 4060",
    basePrice: 28990000,
    originalPrice: 32990000,
    display: '16" WQXGA 165Hz',
    battery: "80Wh",
    weight: "2.4kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming mỏng nhẹ, hiệu năng cao trong tầm giá hợp lý.",
  }),
  seed({
    id: "lv8",
    slug: "lenovo-ideapad-slim-5",
    name: "Lenovo IdeaPad Slim 5",
    brand: "Lenovo",
    needs: ["Sinh viên", "Văn phòng"],
    cpu: "AMD Ryzen 7",
    gpu: "Intel Arc",
    basePrice: 17990000,
    display: '14" WUXGA OLED',
    battery: "57Wh",
    weight: "1.46kg",
    warranty: "24 tháng",
    description: "Laptop sinh viên với màn OLED đẹp mắt, mỏng nhẹ tiện di chuyển.",
  }),
  seed({
    id: "lv9",
    slug: "lenovo-ideapad-flex-5",
    name: "Lenovo IdeaPad Flex 5",
    brand: "Lenovo",
    needs: ["Cảm ứng", "Sinh viên"],
    cpu: "Intel Core i5",
    gpu: "Iris Xe",
    basePrice: 16990000,
    display: '14" WUXGA cảm ứng',
    battery: "52Wh",
    weight: "1.55kg",
    warranty: "24 tháng",
    description: "Convertible 2-in-1 cho sinh viên ghi chú, vẽ và xem phim linh hoạt.",
  }),
  seed({
    id: "lv10",
    slug: "lenovo-thinkbook-14-gen-7",
    name: "Lenovo ThinkBook 14 Gen 7",
    brand: "Lenovo",
    needs: ["Văn phòng", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 24990000,
    display: '14" 2.8K OLED',
    battery: "60Wh",
    weight: "1.38kg",
    warranty: "24 tháng",
    badge: "Mới",
    description: "Laptop doanh nghiệp trẻ trung, tích hợp Copilot AI và OLED 2.8K.",
  }),

  // ========== MSI (10) — Gaming áp đảo ==========
  seed({
    id: "ms1",
    slug: "msi-titan-18-hx",
    name: "MSI Titan 18 HX",
    brand: "MSI",
    needs: ["Gaming", "Đồ họa"],
    cpu: "Intel Core i9",
    gpu: "RTX 4090",
    basePrice: 119990000,
    display: '18" 4K Mini-LED 120Hz',
    battery: "99Wh",
    weight: "3.6kg",
    warranty: "24 tháng",
    badge: "Mới",
    rating: 4.9,
    description: "Titan của giới gaming, RTX 4090 cùng màn 4K Mini-LED đỉnh cao.",
  }),
  seed({
    id: "ms2",
    slug: "msi-raider-ge78-hx",
    name: "MSI Raider GE78 HX",
    brand: "MSI",
    needs: ["Gaming"],
    cpu: "Intel Core i9",
    gpu: "RTX 4080",
    basePrice: 79990000,
    display: '17" QHD+ 240Hz Mini-LED',
    battery: "99Wh",
    weight: "3.1kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    rating: 4.8,
    description: "Gaming màn 17 inch sống động, dải đèn RGB rực rỡ phía sau.",
  }),
  seed({
    id: "ms3",
    slug: "msi-stealth-16-ai-studio",
    name: "MSI Stealth 16 AI Studio",
    brand: "MSI",
    needs: ["Gaming", "Laptop AI", "Mỏng nhẹ"],
    cpu: "Intel Core Ultra 9",
    gpu: "RTX 4070",
    basePrice: 58990000,
    display: '16" 4K OLED',
    battery: "99Wh",
    weight: "1.9kg",
    warranty: "24 tháng",
    badge: "Mới",
    description: "Gaming mỏng nhẹ tích hợp NPU cho stream và sáng tạo AI.",
  }),
  seed({
    id: "ms4",
    slug: "msi-vector-16-hx",
    name: "MSI Vector 16 HX",
    brand: "MSI",
    needs: ["Gaming"],
    cpu: "Intel Core i9",
    gpu: "RTX 4070",
    basePrice: 49990000,
    display: '16" QHD+ 240Hz',
    battery: "90Wh",
    weight: "2.7kg",
    warranty: "24 tháng",
    description: "Hiệu năng gaming chuẩn desktop trong thân máy laptop.",
  }),
  seed({
    id: "ms5",
    slug: "msi-katana-15",
    name: "MSI Katana 15",
    brand: "MSI",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i7",
    gpu: "RTX 4060",
    basePrice: 26990000,
    originalPrice: 29990000,
    display: '15.6" FHD 144Hz',
    battery: "53Wh",
    weight: "2.25kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming chiến binh giá hợp lý cho game thủ trẻ.",
  }),
  seed({
    id: "ms6",
    slug: "msi-cyborg-15",
    name: "MSI Cyborg 15",
    brand: "MSI",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i7",
    gpu: "RTX 4050",
    basePrice: 22490000,
    originalPrice: 25990000,
    display: '15.6" FHD 144Hz',
    battery: "53Wh",
    weight: "1.98kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Thiết kế trong suốt độc đáo, RTX 4050 đủ chiến mọi game phổ biến.",
  }),
  seed({
    id: "ms7",
    slug: "msi-creator-m16",
    name: "MSI Creator M16",
    brand: "MSI",
    needs: ["Đồ họa"],
    cpu: "Intel Core i7",
    gpu: "RTX 4060",
    basePrice: 36990000,
    display: '16" QHD+ 165Hz DCI-P3 100%',
    battery: "65Wh",
    weight: "2.1kg",
    warranty: "24 tháng",
    description: "Laptop sáng tạo nội dung với màu chuẩn DCI-P3 cho designer.",
  }),
  seed({
    id: "ms8",
    slug: "msi-prestige-14-ai-evo",
    name: "MSI Prestige 14 AI Evo",
    brand: "MSI",
    needs: ["Mỏng nhẹ", "Văn phòng", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 29990000,
    display: '14" 2.8K OLED',
    battery: "72Wh",
    weight: "1.3kg",
    warranty: "24 tháng",
    badge: "Mới",
    description: "Ultrabook AI mỏng nhẹ cho doanh nhân hiện đại, pin cả ngày.",
  }),
  seed({
    id: "ms9",
    slug: "msi-modern-15",
    name: "MSI Modern 15",
    brand: "MSI",
    needs: ["Văn phòng", "Sinh viên"],
    cpu: "Intel Core i5",
    gpu: "Iris Xe",
    basePrice: 15490000,
    display: '15.6" FHD IPS',
    battery: "52Wh",
    weight: "1.7kg",
    warranty: "24 tháng",
    description: "Laptop văn phòng tinh giản, hiệu năng ổn định cho công việc hằng ngày.",
  }),
  seed({
    id: "ms10",
    slug: "msi-summit-e14-flip-evo",
    name: "MSI Summit E14 Flip Evo",
    brand: "MSI",
    needs: ["Cảm ứng", "Văn phòng"],
    cpu: "Intel Core i7",
    gpu: "Iris Xe",
    basePrice: 33990000,
    display: '14" 2.8K OLED cảm ứng',
    battery: "70Wh",
    weight: "1.5kg",
    warranty: "24 tháng",
    description: "Convertible 2-in-1 cao cấp cho doanh nhân thuyết trình linh hoạt.",
  }),

  // ========== Acer (10) — Mix: Predator gaming, Swift slim, Spin touch ==========
  seed({
    id: "ac1",
    slug: "acer-predator-helios-18",
    name: "Acer Predator Helios 18",
    brand: "Acer",
    needs: ["Gaming", "Đồ họa"],
    cpu: "Intel Core i9",
    gpu: "RTX 4080",
    basePrice: 72990000,
    display: '18" WQXGA 250Hz Mini-LED',
    battery: "90Wh",
    weight: "3.3kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    rating: 4.8,
    description: "Quái vật gaming màn 18 inch, tản AeroBlade 3D mạnh mẽ.",
  }),
  seed({
    id: "ac2",
    slug: "acer-predator-helios-neo-16",
    name: "Acer Predator Helios Neo 16",
    brand: "Acer",
    needs: ["Gaming"],
    cpu: "Intel Core i7",
    gpu: "RTX 4060",
    basePrice: 32990000,
    display: '16" WQXGA 165Hz',
    battery: "76Wh",
    weight: "2.6kg",
    warranty: "24 tháng",
    description: "Gaming tầm trung sức mạnh đỉnh, đèn RGB 4 vùng.",
  }),
  seed({
    id: "ac3",
    slug: "acer-nitro-v-15",
    name: "Acer Nitro V 15",
    brand: "Acer",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i5",
    gpu: "RTX 4050",
    basePrice: 19990000,
    originalPrice: 22990000,
    display: '15.6" FHD 144Hz',
    battery: "57Wh",
    weight: "2.1kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming entry hợp túi tiền sinh viên, RTX 4050 ổn định.",
  }),
  seed({
    id: "ac4",
    slug: "acer-swift-go-14",
    name: "Acer Swift Go 14",
    brand: "Acer",
    needs: ["Mỏng nhẹ", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 22990000,
    display: '14" 2.8K OLED',
    battery: "65Wh",
    weight: "1.3kg",
    warranty: "24 tháng",
    badge: "Mới",
    description: "Ultrabook AI mỏng nhẹ, webcam 1440p và phím Copilot riêng.",
  }),
  seed({
    id: "ac5",
    slug: "acer-swift-x-14",
    name: "Acer Swift X 14",
    brand: "Acer",
    needs: ["Đồ họa", "Mỏng nhẹ"],
    cpu: "Intel Core Ultra 7",
    gpu: "RTX 4050",
    basePrice: 31990000,
    display: '14.5" 2.8K OLED 120Hz',
    battery: "76Wh",
    weight: "1.5kg",
    warranty: "24 tháng",
    description: "Creator laptop mỏng nhẹ với RTX 4050, màu chuẩn 100% DCI-P3.",
  }),
  seed({
    id: "ac6",
    slug: "acer-aspire-5",
    name: "Acer Aspire 5",
    brand: "Acer",
    needs: ["Sinh viên", "Văn phòng"],
    cpu: "Intel Core i5",
    gpu: "Iris Xe",
    basePrice: 13990000,
    originalPrice: 15990000,
    display: '15.6" FHD IPS',
    battery: "50Wh",
    weight: "1.7kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Laptop văn phòng giá rẻ, đáng tin cậy cho học sinh sinh viên.",
  }),
  seed({
    id: "ac7",
    slug: "acer-aspire-7-gaming",
    name: "Acer Aspire 7 Gaming",
    brand: "Acer",
    needs: ["Gaming", "Sinh viên"],
    cpu: "AMD Ryzen 7",
    gpu: "RTX 3050",
    basePrice: 17990000,
    display: '15.6" FHD 144Hz',
    battery: "48Wh",
    weight: "2.1kg",
    warranty: "24 tháng",
    description: "Gaming giá sinh viên, đủ mạnh cho học tập và game eSports.",
  }),
  seed({
    id: "ac8",
    slug: "acer-spin-5",
    name: "Acer Spin 5",
    brand: "Acer",
    needs: ["Cảm ứng", "Mỏng nhẹ"],
    cpu: "Intel Core i7",
    gpu: "Iris Xe",
    basePrice: 26990000,
    display: '14" 2.5K cảm ứng',
    battery: "56Wh",
    weight: "1.5kg",
    warranty: "24 tháng",
    description: "Convertible 360° với bút stylus tích hợp, lý tưởng cho ghi chú.",
  }),
  seed({
    id: "ac9",
    slug: "acer-travelmate-p4",
    name: "Acer TravelMate P4",
    brand: "Acer",
    needs: ["Văn phòng"],
    cpu: "Intel Core i5",
    gpu: "Iris Xe",
    basePrice: 19990000,
    display: '14" WUXGA IPS',
    battery: "65Wh",
    weight: "1.6kg",
    warranty: "36 tháng",
    description: "Laptop doanh nghiệp bền bỉ, bảo mật vTNM và bảo hành 3 năm.",
  }),
  seed({
    id: "ac10",
    slug: "acer-chromebook-plus-515",
    name: "Acer Chromebook Plus 515",
    brand: "Acer",
    needs: ["Văn phòng", "Sinh viên"],
    cpu: "Intel Core i5",
    gpu: "Iris Xe",
    basePrice: 11990000,
    display: '15.6" FHD IPS',
    battery: "57Wh",
    weight: "1.75kg",
    warranty: "24 tháng",
    description: "Chromebook hiệu năng cao, khởi động nhanh, pin trâu cho công việc nhẹ.",
  }),

  // ========== HP (10) — Business EliteBook & Spectre touch ==========
  seed({
    id: "hp1",
    slug: "hp-spectre-x360-14",
    name: "HP Spectre x360 14",
    brand: "HP",
    needs: ["Cảm ứng", "Mỏng nhẹ", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 42990000,
    display: '14" 2.8K OLED cảm ứng',
    battery: "68Wh",
    weight: "1.4kg",
    warranty: "24 tháng",
    badge: "Mới",
    rating: 4.8,
    description: "Convertible cao cấp với thiết kế kim cương sang trọng, bút HP MPP đi kèm.",
  }),
  seed({
    id: "hp2",
    slug: "hp-envy-x360-15",
    name: "HP Envy x360 15",
    brand: "HP",
    needs: ["Cảm ứng", "Sinh viên"],
    cpu: "AMD Ryzen 7",
    gpu: "Intel Arc",
    basePrice: 23990000,
    display: '15.6" FHD OLED cảm ứng',
    battery: "55Wh",
    weight: "1.9kg",
    warranty: "24 tháng",
    description: "2-in-1 đa năng cho sinh viên, màn OLED rực rỡ trong tầm giá.",
  }),
  seed({
    id: "hp3",
    slug: "hp-elitebook-840-g11",
    name: "HP EliteBook 840 G11",
    brand: "HP",
    needs: ["Văn phòng", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 36990000,
    display: '14" WUXGA chống chói',
    battery: "56Wh",
    weight: "1.36kg",
    warranty: "36 tháng",
    description: "Laptop doanh nhân với HP Wolf Security và NPU AI cho công việc thông minh.",
  }),
  seed({
    id: "hp4",
    slug: "hp-elitebook-1040-g11",
    name: "HP EliteBook 1040 G11",
    brand: "HP",
    needs: ["Văn phòng", "Mỏng nhẹ"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 45990000,
    display: '14" 2.8K OLED',
    battery: "68Wh",
    weight: "1.35kg",
    warranty: "36 tháng",
    rating: 4.8,
    description: "Flagship EliteBook siêu mỏng, vỏ magnesium siêu nhẹ cho CEO.",
  }),
  seed({
    id: "hp5",
    slug: "hp-probook-450-g11",
    name: "HP ProBook 450 G11",
    brand: "HP",
    needs: ["Văn phòng", "Sinh viên"],
    cpu: "Intel Core i5",
    gpu: "Iris Xe",
    basePrice: 18990000,
    display: '15.6" FHD IPS',
    battery: "51Wh",
    weight: "1.74kg",
    warranty: "24 tháng",
    description: "Laptop văn phòng đáng tin cậy, bảo mật vân tay tiêu chuẩn doanh nghiệp.",
  }),
  seed({
    id: "hp6",
    slug: "hp-pavilion-plus-14",
    name: "HP Pavilion Plus 14",
    brand: "HP",
    needs: ["Sinh viên", "Mỏng nhẹ"],
    cpu: "Intel Core i7",
    gpu: "Iris Xe",
    basePrice: 19990000,
    originalPrice: 22990000,
    display: '14" 2.8K OLED 90Hz',
    battery: "51Wh",
    weight: "1.41kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Laptop sinh viên với màn OLED 2.8K hiếm có trong tầm giá.",
  }),
  seed({
    id: "hp7",
    slug: "hp-omen-16",
    name: "HP OMEN 16",
    brand: "HP",
    needs: ["Gaming"],
    cpu: "Intel Core i7",
    gpu: "RTX 4070",
    basePrice: 39990000,
    display: '16" QHD 240Hz',
    battery: "83Wh",
    weight: "2.4kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    rating: 4.7,
    description: "Gaming hiệu năng cao, tản nhiệt OMEN Tempest tối ưu cho session dài.",
  }),
  seed({
    id: "hp8",
    slug: "hp-omen-transcend-14",
    name: "HP OMEN Transcend 14",
    brand: "HP",
    needs: ["Gaming", "Mỏng nhẹ"],
    cpu: "Intel Core Ultra 9",
    gpu: "RTX 4060",
    basePrice: 44990000,
    display: '14" 2.8K OLED 120Hz',
    battery: "68Wh",
    weight: "1.6kg",
    warranty: "24 tháng",
    badge: "Mới",
    description: "Gaming mỏng nhẹ nhất phân khúc, OLED 2.8K cho cả game và sáng tạo.",
  }),
  seed({
    id: "hp9",
    slug: "hp-victus-16",
    name: "HP Victus 16",
    brand: "HP",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i5",
    gpu: "RTX 4050",
    basePrice: 21990000,
    originalPrice: 24990000,
    display: '16.1" FHD 144Hz',
    battery: "70Wh",
    weight: "2.37kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming sinh viên giá hợp lý, màn 16 inch lớn cho trải nghiệm sống động.",
  }),
  seed({
    id: "hp10",
    slug: "hp-zbook-firefly-14-g11",
    name: "HP ZBook Firefly 14 G11",
    brand: "HP",
    needs: ["Đồ họa", "Văn phòng"],
    cpu: "Intel Core Ultra 7",
    gpu: "RTX 3050",
    basePrice: 41990000,
    display: '14" 2.8K OLED chuẩn màu',
    battery: "56Wh",
    weight: "1.4kg",
    warranty: "36 tháng",
    description: "Mobile workstation mỏng nhẹ cho kiến trúc sư, kỹ sư CAD di động.",
  }),

  // ========== Dell (10) — XPS slim, Latitude business, Alienware gaming ==========
  seed({
    id: "dl1",
    slug: "dell-xps-13-plus",
    name: "Dell XPS 13 Plus",
    brand: "Dell",
    needs: ["Mỏng nhẹ", "Văn phòng"],
    cpu: "Intel Core i7",
    gpu: "Iris Xe",
    basePrice: 28990000,
    display: '13.4" 3.5K OLED',
    battery: "55Wh",
    weight: "1.24kg",
    warranty: "24 tháng",
    rating: 4.6,
    description: "Ultrabook tối giản với phím cảm ứng độc đáo và OLED 3.5K.",
  }),
  seed({
    id: "dl2",
    slug: "dell-xps-14",
    name: "Dell XPS 14",
    brand: "Dell",
    needs: ["Mỏng nhẹ", "Đồ họa", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "RTX 4050",
    basePrice: 46990000,
    display: '14.5" 3.2K OLED cảm ứng',
    battery: "70Wh",
    weight: "1.7kg",
    warranty: "24 tháng",
    badge: "Mới",
    rating: 4.8,
    description: "XPS thế hệ mới: viền siêu mỏng, phím cảm ứng và sức mạnh sáng tạo.",
  }),
  seed({
    id: "dl3",
    slug: "dell-xps-16",
    name: "Dell XPS 16",
    brand: "Dell",
    needs: ["Đồ họa", "Mỏng nhẹ"],
    cpu: "Intel Core Ultra 9",
    gpu: "RTX 4070",
    basePrice: 64990000,
    display: '16.3" 4K OLED cảm ứng',
    battery: "99Wh",
    weight: "2.1kg",
    warranty: "24 tháng",
    rating: 4.8,
    description: "Flagship XPS cho creator, OLED 4K viền vô cực đỉnh cao thẩm mỹ.",
  }),
  seed({
    id: "dl4",
    slug: "dell-latitude-7450",
    name: "Dell Latitude 7450",
    brand: "Dell",
    needs: ["Văn phòng", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 38990000,
    display: '14" QHD+ chống chói',
    battery: "60Wh",
    weight: "1.36kg",
    warranty: "36 tháng",
    description: "Latitude doanh nhân với NPU AI và bảo mật ControlVault tích hợp.",
  }),
  seed({
    id: "dl5",
    slug: "dell-latitude-9450-2-in-1",
    name: "Dell Latitude 9450 2-in-1",
    brand: "Dell",
    needs: ["Cảm ứng", "Văn phòng"],
    cpu: "Intel Core Ultra 7",
    gpu: "Intel Arc",
    basePrice: 52990000,
    display: '14" QHD+ cảm ứng',
    battery: "72Wh",
    weight: "1.5kg",
    warranty: "36 tháng",
    description: "Convertible cao cấp cho CEO, vỏ nhôm CNC và camera 8MP.",
  }),
  seed({
    id: "dl6",
    slug: "dell-inspiron-14-plus",
    name: "Dell Inspiron 14 Plus",
    brand: "Dell",
    needs: ["Sinh viên", "Văn phòng"],
    cpu: "Intel Core i7",
    gpu: "Iris Xe",
    basePrice: 19990000,
    display: '14" 2.2K IPS',
    battery: "54Wh",
    weight: "1.5kg",
    warranty: "24 tháng",
    description: "Laptop sinh viên hiện đại, màn 16:10 cao ráo, vỏ nhôm cao cấp.",
  }),
  seed({
    id: "dl7",
    slug: "dell-inspiron-16-2-in-1",
    name: "Dell Inspiron 16 2-in-1",
    brand: "Dell",
    needs: ["Cảm ứng", "Sinh viên"],
    cpu: "AMD Ryzen 7",
    gpu: "Intel Arc",
    basePrice: 22990000,
    display: '16" FHD+ cảm ứng',
    battery: "64Wh",
    weight: "2.1kg",
    warranty: "24 tháng",
    description: "2-in-1 màn lớn cho sinh viên ghi chú, vẽ và xem phim thoải mái.",
  }),
  seed({
    id: "dl8",
    slug: "dell-vostro-3530",
    name: "Dell Vostro 3530",
    brand: "Dell",
    needs: ["Văn phòng", "Sinh viên"],
    cpu: "Intel Core i5",
    gpu: "Iris Xe",
    basePrice: 14990000,
    display: '15.6" FHD IPS',
    battery: "41Wh",
    weight: "1.66kg",
    warranty: "24 tháng",
    description: "Laptop văn phòng giá tốt cho SME và sinh viên mới ra trường.",
  }),
  seed({
    id: "dl9",
    slug: "dell-alienware-m18-r2",
    name: "Dell Alienware m18 R2",
    brand: "Dell",
    needs: ["Gaming", "Đồ họa"],
    cpu: "Intel Core i9",
    gpu: "RTX 4090",
    basePrice: 109990000,
    display: '18" QHD+ 165Hz',
    battery: "97Wh",
    weight: "4.0kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    rating: 4.9,
    description: "Quái vật Alienware với RTX 4090, tản nhiệt Cryo-tech đẳng cấp.",
  }),
  seed({
    id: "dl10",
    slug: "dell-g16-7630",
    name: "Dell G16 7630",
    brand: "Dell",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i7",
    gpu: "RTX 4060",
    basePrice: 29990000,
    originalPrice: 33990000,
    display: '16" QHD+ 240Hz',
    battery: "86Wh",
    weight: "2.8kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming Dell G-Series sức mạnh khủng với giá hấp dẫn.",
  }),

  // ========== GIGABYTE (10) — Gaming Aorus & Creator Aero ==========
  seed({
    id: "gb1",
    slug: "gigabyte-aorus-master-18",
    name: "GIGABYTE AORUS Master 18",
    brand: "GIGABYTE",
    needs: ["Gaming", "Đồ họa"],
    cpu: "Intel Core i9",
    gpu: "RTX 4090",
    basePrice: 99990000,
    display: '18" QHD+ 240Hz Mini-LED',
    battery: "99Wh",
    weight: "3.2kg",
    warranty: "24 tháng",
    badge: "Mới",
    rating: 4.9,
    description: "Flagship Aorus với RTX 4090, tản WindForce Infinity và đèn RGB toàn thân.",
  }),
  seed({
    id: "gb2",
    slug: "gigabyte-aorus-17x",
    name: "GIGABYTE AORUS 17X",
    brand: "GIGABYTE",
    needs: ["Gaming"],
    cpu: "Intel Core i9",
    gpu: "RTX 4080",
    basePrice: 72990000,
    display: '17" QHD 240Hz',
    battery: "99Wh",
    weight: "2.8kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming màn 17 inch hiệu năng đỉnh, hệ thống làm mát hơi nước.",
  }),
  seed({
    id: "gb3",
    slug: "gigabyte-aorus-16x",
    name: "GIGABYTE AORUS 16X",
    brand: "GIGABYTE",
    needs: ["Gaming"],
    cpu: "Intel Core i7",
    gpu: "RTX 4070",
    basePrice: 42990000,
    display: '16" QHD+ 165Hz',
    battery: "76Wh",
    weight: "2.4kg",
    warranty: "24 tháng",
    description: "Gaming hiệu năng cao với GenAI tích hợp, gợi ý chiến thuật trong game.",
  }),
  seed({
    id: "gb4",
    slug: "gigabyte-aorus-15-bsf",
    name: "GIGABYTE AORUS 15 BSF",
    brand: "GIGABYTE",
    needs: ["Gaming"],
    cpu: "Intel Core i7",
    gpu: "RTX 4070",
    basePrice: 36990000,
    originalPrice: 39990000,
    display: '15.6" QHD 165Hz',
    battery: "76Wh",
    weight: "2.2kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming màn 15 inch QHD với RTX 4070, lựa chọn cân bằng cho game thủ.",
  }),
  seed({
    id: "gb5",
    slug: "gigabyte-g6x-9kg",
    name: "GIGABYTE G6X 9KG",
    brand: "GIGABYTE",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i7",
    gpu: "RTX 4060",
    basePrice: 27990000,
    display: '16" WUXGA 165Hz',
    battery: "73Wh",
    weight: "2.3kg",
    warranty: "24 tháng",
    description: "Gaming sinh viên với RTX 4060, màn 16 inch tỷ lệ 16:10 hiện đại.",
  }),
  seed({
    id: "gb6",
    slug: "gigabyte-g5-kf",
    name: "GIGABYTE G5 KF",
    brand: "GIGABYTE",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i7",
    gpu: "RTX 4060",
    basePrice: 24990000,
    originalPrice: 27990000,
    display: '15.6" FHD 144Hz',
    battery: "54Wh",
    weight: "2.1kg",
    warranty: "24 tháng",
    badge: "Flash Sale",
    description: "Gaming giá tốt nhất phân khúc RTX 4060, lý tưởng cho sinh viên.",
  }),
  seed({
    id: "gb7",
    slug: "gigabyte-g6-kf",
    name: "GIGABYTE G6 KF",
    brand: "GIGABYTE",
    needs: ["Gaming", "Sinh viên"],
    cpu: "Intel Core i7",
    gpu: "RTX 4060",
    basePrice: 26490000,
    display: '16" FHD+ 165Hz',
    battery: "54Wh",
    weight: "2.3kg",
    warranty: "24 tháng",
    description: "Gaming 16 inch tỷ lệ 16:10, không gian hiển thị rộng cho học tập + game.",
  }),
  seed({
    id: "gb8",
    slug: "gigabyte-aero-16-oled",
    name: "GIGABYTE AERO 16 OLED",
    brand: "GIGABYTE",
    needs: ["Đồ họa", "Mỏng nhẹ"],
    cpu: "Intel Core i9",
    gpu: "RTX 4070",
    basePrice: 54990000,
    display: '16" 4K AMOLED chuẩn Pantone',
    battery: "99Wh",
    weight: "2.0kg",
    warranty: "24 tháng",
    badge: "Mới",
    rating: 4.8,
    description: "Creator laptop với 4K AMOLED Pantone, X-Rite, lý tưởng cho dựng phim.",
  }),
  seed({
    id: "gb9",
    slug: "gigabyte-aero-14-oled",
    name: "GIGABYTE AERO 14 OLED",
    brand: "GIGABYTE",
    needs: ["Đồ họa", "Mỏng nhẹ", "Laptop AI"],
    cpu: "Intel Core Ultra 7",
    gpu: "RTX 4050",
    basePrice: 39990000,
    display: '14" 2.8K OLED 90Hz',
    battery: "63Wh",
    weight: "1.5kg",
    warranty: "24 tháng",
    description: "Creator mỏng nhẹ tích hợp AI Engine cho upscale ảnh và video.",
  }),
  seed({
    id: "gb10",
    slug: "gigabyte-u7",
    name: "GIGABYTE U7",
    brand: "GIGABYTE",
    needs: ["Mỏng nhẹ", "Văn phòng"],
    cpu: "Intel Core i7",
    gpu: "Iris Xe",
    basePrice: 22990000,
    display: '17.3" FHD IPS',
    battery: "73Wh",
    weight: "1.9kg",
    warranty: "24 tháng",
    description: "Laptop văn phòng màn lớn 17 inch nhưng vẫn mỏng nhẹ ấn tượng.",
  }),
];

export const brands: Brand[] = ["ASUS", "Lenovo", "MSI", "Acer", "HP", "Dell", "GIGABYTE"];
export const cpus: CpuFamily[] = [
  "Intel Core i5",
  "Intel Core i7",
  "Intel Core i9",
  "Intel Core Ultra 7",
  "Intel Core Ultra 9",
  "AMD Ryzen 7",
  "AMD Ryzen 9",
  "AMD Ryzen AI 9",
  "Snapdragon X Elite",
];
export const gpus: GpuFamily[] = [
  "Iris Xe",
  "Intel Arc",
  "RTX 3050",
  "RTX 4050",
  "RTX 4060",
  "RTX 4070",
  "RTX 4080",
  "RTX 4090",
];
export const rams: Array<8 | 16 | 32 | 64> = [8, 16, 32, 64];
export const needs: Need[] = [
  "Văn phòng",
  "Gaming",
  "Mỏng nhẹ",
  "Đồ họa",
  "Sinh viên",
  "Laptop AI",
];

// Cache cho các sản phẩm lấy từ API (backend)
const apiProductsCache = new Map<string, Product>();

export function cacheApiProducts(productsList: Product[]) {
  productsList.forEach((p) => {
    apiProductsCache.set(p.id, p);
  });
}

export function cacheApiProduct(p: Product) {
  apiProductsCache.set(p.id, p);
}

export function getProductBySlug(slug: string): Product | undefined {
  const mockProduct = products.find((p) => p.slug === slug);
  if (mockProduct) return mockProduct;
  return Array.from(apiProductsCache.values()).find((p) => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
  const mockProduct = products.find((p) => p.id === id);
  if (mockProduct) return mockProduct;
  return apiProductsCache.get(id);
}

export function variantOriginalPrice(product: Product, variantIndex: number): number {
  const v = product.variants[variantIndex];
  const origBase = product.giaGoc !== undefined ? product.giaGoc : product.basePrice;
  return origBase + (v ? v.priceDelta : 0);
}

export function variantPrice(product: Product, variantIndex: number): number {
  const v = product.variants[variantIndex];
  const original =
    (product.giaGoc !== undefined ? product.giaGoc : product.basePrice) + (v ? v.priceDelta : 0);
  if (product.phanTramGiam && product.phanTramGiam > 0) {
    return Math.round(original * (1 - product.phanTramGiam / 100));
  }
  return product.basePrice + (v ? v.priceDelta : 0);
}

/** Deterministic placeholder gradient (no images bundled). */
export function gradientFor(seed: string): string {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) >>> 0;
  const h1 = h % 360;
  const h2 = (h1 + 40) % 360;
  return `linear-gradient(135deg, oklch(0.85 0.04 ${h1}) 0%, oklch(0.55 0.06 ${h2}) 100%)`;
}
